apiVersion: v1
kind: Secret
metadata:
  name: {{ include "signserver.fullname" . }}-secrets
  labels:
    app: {{ include "signserver.name" . }}
type: Opaque
stringData:
  # Senha do Banco RDS
  db-password: {{ .Values.DATABASE_PASSWORD }}
  # Arquivo da CA para ser montado como volume
  admin-ca.crt: |
    {{ .Values.security.adminCaCert | nindent 4 }}