apiVersion: v1
kind: Service
metadata:
  name: {{ include "signserver.fullname" . }}
  labels:
    app: {{ include "signserver.name" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ include "signserver.name" . }}