image:
  repository: primekey/signserver-ce
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  # Usar NLB é importante para fazer "TCP Passthrough", permitindo que o 
  # SignServer valide o certificado do cliente, e não o LoadBalancer da AWS.
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # --- ADICIONE ESTAS LINHAS ---
    # Define que o Health Check deve ser feito via TCP (apenas ver se a porta abre)
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: TCP
    # Força o Health Check a ser feito na porta 8082 (HTTP normal),
    # ignorando a exigência de certificado da porta 8443.
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8082"
    # Aumenta a tolerância, pois o SignServer demora para subir
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
  httpPort: 8082
  httpsPort: 8444

persistence:
  enabled: true
  size: 10Gi
  storageClass: gp2

# Config de la connection à la BD (AWS RDS)

DATABASE_JDBC_URL: '' 
DATABASE_USER: ''
DATABASE_PASSWORD: ''
DATABASE_DRIVER: 'org.postgresql.Driver'

# Sécurité et contrôle d'accès 
security:
  # O DN (Distinguished Name) EXACT de votre certificat numérique d'administrateur.
  adminDn: ""
  
  # Collez ici le contenu du certificat de l'AC (au format PEM) qui a émis votre certificat.
  # WildFly utilisera cela pour faire confiance à votre certificat client.
  adminCaCert: ""
